---

- hosts: all
  gather_facts: yes
  user: ubuntu
  become: yes

  tasks:
    - name: module load
      lineinfile:
        dest: /etc/modules
        line: br_netfilter
    - modprobe:
        name: br_netfilter

    - name: prep hosts
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        sysctl_file: /etc/sysctl.conf
        value: 1
        reload: yes

    - name: prep container runtime
      lineinfile:
        dest: /etc/modules
        line: overlay

    - modprobe:
        name: overlay
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_file: /etc/sysctl.conf
        reload: yes

    - name: apk cache update
      apt:
        update_cache: yes


# setup containerd
    - name: pkgs
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: container-d
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    - apt:
        name: containerd.io

    - file:
        dest: /etc/containerd
        state: directory
    - shell: "containerd config default > /etc/containerd/config.toml"
    - systemd:
        service: containerd
        state: restarted
# [plugins.cri]
  #systemd_cgroup = true

  ### install k8s
    - name: setup kubeadm kubelet kubectl
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    - apt:
        name: "{{ item }}"
      loop:
        - kubelet
        - kubeadm
        - kubectl
